services:
  backend:
    build: site
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mc_server:
    image: itzg/minecraft-server
    container_name: mc_server
    environment:
      - EULA=TRUE
      - TYPE=PAPER
      - VERSION=1.20.1
      - RCON_PASSWORD=password
    volumes:
      - ./data:/data