FROM python:3.12-slim

COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir

COPY ./backend .
COPY ./frontend frontend
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]